# Generated by Django 5.0.2 on 2024-02-18 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldies_day',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
