# Generated by Django 5.0.2 on 2024-02-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_expriance_remove_oldies_day_label_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='expriance',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
