# Generated by Django 5.0.2 on 2024-02-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_expriance_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expriance',
            name='url',
        ),
        migrations.AddField(
            model_name='expriance',
            name='html_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
