# Generated by Django 5.0.2 on 2024-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
