# Generated by Django 5.0.2 on 2024-02-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_futures'),
    ]

    operations = [
        migrations.AddField(
            model_name='futures',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
