# Generated by Django 5.0.1 on 2024-02-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_futures_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='des',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ImageField(upload_to='media/BG0A9014.JPG'),
        ),
    ]
