# Generated by Django 5.0.1 on 2024-02-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_contact_homepage_des_alter_homepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='expriance',
            name='des',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expriance',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
