# Generated by Django 5.0.1 on 2024-02-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_expriance_des_expriance_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='founders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=100)),
                ('occupatipon', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
