# Generated by Django 5.0.1 on 2024-02-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_founders'),
    ]

    operations = [
        migrations.AddField(
            model_name='founders',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='founders',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
