# Generated by Django 5.0.1 on 2024-02-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_founders_desc_founders_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='founders',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='founders',
            name='title',
        ),
    ]
