# Generated by Django 5.0.1 on 2024-02-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_titles_remove_founders_desc_remove_founders_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='title2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
