# Generated by Django 5.0.1 on 2024-02-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_titles_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='desc2',
            field=models.TextField(null=True),
        ),
    ]
