# Generated by Django 5.0.2 on 2024-02-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_rename_description_contact_text_remove_contact_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
